<a href="https://colab.research.google.com/github/lekh-ch/webtask/blob/main/Amazondataset_NB1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# ====================================================
# Import Required Libraries
# ====================================================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

plt.style.use("ggplot")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows",10)

In [5]:
# ==========================================
# Load Dataset
# ==========================================

df = pd.read_csv("/content/Amazon.csv")

df.head()

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,0.10,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,0.15,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,0.25,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411

In [6]:
print("Rows :",df.shape[0])
print("Columns :",df.shape[1])

Rows : 100000
Columns : 20

In [7]:
df.columns

Index(['OrderID', 'OrderDate', 'CustomerID', 'CustomerName', 'ProductID',
       'ProductName', 'Category', 'Brand', 'Quantity', 'UnitPrice', 'Discount',
       'Tax', 'ShippingCost', 'TotalAmount', 'PaymentMethod', 'OrderStatus',
       'City', 'State', 'Country', 'SellerID'],
      dtype='object')

In [8]:
df.dtypes

OrderID         object
OrderDate       object
CustomerID      object
CustomerName    object
ProductID       object
                 ...
OrderStatus     object
City            object
State           object
Country         object
SellerID        object
Length: 20, dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   OrderID        100000 non-null  object
 1   OrderDate      100000 non-null  object
 2   CustomerID     100000 non-null  object
 3   CustomerName   100000 non-null  object
 4   ProductID      100000 non-null  object
 5   ProductName    100000 non-null  object
 6   Category       100000 non-null  object
 7   Brand          100000 non-null  object
 8   Quantity       100000 non-null  int64
 9   UnitPrice      100000 non-null  float64
 10  Discount       100000 non-null  float64
 11  Tax            100000 non-null  float64
 12  ShippingCost   100000 non-null  float64
 13  TotalAmount    100000 non-null  float64
 14  PaymentMethod  100000 non-null  object
 15  OrderStatus    100000 non-null  object
 16  City           100000 non-null  object
 17  State          100000 non-null  object
 18  Country        100000 non-null  object
 19  SellerID       100000 non-null  object
dtypes: float64(5), int64(1), object(14)
memory usage: 15.3+ MB

In [10]:
df.describe()

,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,3.001400,302.905748,0.074226,68.468902,7.406660,918.256479
std,1.413548,171.840797,0.082583,74.131180,4.324057,724.508332
min,1.000000,5.000000,0.000000,0.000000,0.000000,4.270000
25%,2.000000,154.190000,0.000000,15.920000,3.680000,340.890000
50%,3.000000,303.070000,0.050000,45.250000,7.300000,714.315000
75%,4.000000,451.500000,0.100000,96.060000,11.150000,1349.765000
max,5.000000,599.990000,0.300000,538.460000,15.000000,3534.980000

In [11]:
df.describe(include="object")

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,PaymentMethod,OrderStatus,City,State,Country,SellerID
count,100000,100000,100000,100000,100000,100000,100000,100000,100000,100000,100000,100000,100000,100000
unique,100000,1825,43233,200,50,50,6,10,6,5,20,13,5,1999
top,ORD0099984,2022-04-28,CUST037103,Karan Joshi,P00019,LED Desk Lamp,Electronics,ReadMore,Credit Card,Delivered,Charlotte,TX,United States,SELL01099
freq,1,85,10,556,2098,2098,16853,10204,35038,74628,5110,24896,70058,78

In [12]:
df.sample(10)

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
14867,ORD0014868,2022-07-03,CUST044197,Vihaan Reddy,P00046,Car Charger,Books,BrightLux,1,239.03,0.00,43.03,10.38,292.44,Debit Card,Delivered,Seattle,WA,United States,SELL00371
89024,ORD0089025,2022-11-10,CUST021223,Neha Mehta,P00013,Action Camera,Electronics,Apex,1,211.93,0.05,24.16,6.99,232.48,Debit Card,Delivered,Jacksonville,FL,Australia,SELL00777
8146,ORD0008147,2022-06-04,CUST029800,Aarav Kapoor,P00013,Action Camera,Books,NexPro,5,17.40,0.05,9.92,3.63,96.20,Amazon Pay,Shipped,Seattle,WA,Australia,SELL01041
68950,ORD0068951,2022-06-22,CUST024790,Karan Singh,P00010,Smartwatch,Home & Kitchen,KiddoFun,3,478.28,0.00,114.79,2.37,1552.00,Amazon Pay,Delivered,Seattle,WA,United States,SELL00064
2110,ORD0002111,2020-02-06,CUST017181,Rohit Kapoor,P00009,Portable SSD 1TB,Toys & Games,BrightLux,5,79.59,0.15,27.06,8.97,374.29,Credit Card,Shipped,Chicago,IL,United States,SELL00522
22167,ORD0022168,2021-02-25,CUST021506,Vikas Singh,P00037,Router,Sports & Outdoors,UrbanStyle,5,560.38,0.15,190.53,14.10,2586.25,Debit Card,Delivered,Denver,CO,India,SELL00797
17123,ORD0017124,2022-07-25,CUST018482,Pooja Reddy,P00029,T-Shirt,Toys & Games,ReadMore,2,210.37,0.30,23.56,11.55,329.63,Credit Card,Delivered,Philadelphia,PA,United States,SELL00866
43645,ORD0043646,2024-02-09,CUST018569,Ritika Sharma,P00016,Air Fryer,Sports & Outdoors,KiddoFun,4,213.86,0.00,68.44,4.76,928.64,Credit Card,Shipped,San Francisco,CA,Australia,SELL00338
78636,ORD0078637,2022-03-10,CUST029467,Karan Joshi,P00011,Fitness Band,Clothing,Apex,5,171.99,0.00,0.00,12.19,872.14,Credit Card,Delivered,Houston,TX,United States,SELL01698
6838,ORD0006839,2023-06-26,CUST002744,Aarav Singh,P00047,Memory Card 128GB,Sports & Outdoors,NexPro,3,427.13,0.00,0.00,14.77,1296.16,Credit Card,Delivered,Los Angeles,CA,United States,SELL01177

In [13]:
df.isnull().sum()

OrderID         0
OrderDate       0
CustomerID      0
CustomerName    0
ProductID       0
               ..
OrderStatus     0
City            0
State           0
Country         0
SellerID        0
Length: 20, dtype: int64

In [14]:
(df.isnull().sum()/len(df))*100

OrderID         0.0
OrderDate       0.0
CustomerID      0.0
CustomerName    0.0
ProductID       0.0
               ...
OrderStatus     0.0
City            0.0
State           0.0
Country         0.0
SellerID        0.0
Length: 20, dtype: float64

In [15]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
text_columns= df.select_dtypes(include='object').columns
for col in text_columns:
  df[col]=df[col].str.strip()

In [ ]:
df['OrderDate']=pd.to_datetime(df['OrderDate'])

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

df.dtypes

OrderID                  object
OrderDate        datetime64[ns]
CustomerID               object
CustomerName             object
ProductID                object
ProductName              object
Category                 object
Brand                    object
Quantity                  int64
UnitPrice               float64
Discount                float64
Tax                     float64
ShippingCost            float64
TotalAmount             float64
PaymentMethod            object
OrderStatus              object
City                     object
State                    object
Country                  object
SellerID                 object
Year                      int32
MonthNo                   int32
Month                    object
Quarter                   int32
WeekDay                  object
Weekend                  object
dtype: object

In [ ]:
nums_columns=['Quantity', 'UnitPrice', 'Discount', 'Tax', 'ShippingCost', 'TotalAmount']
for col in nums_columns:
  print(col,(df[col]<0).sum())

Quantity 0
UnitPrice 0
Discount 0
Tax 0
ShippingCost 0
TotalAmount 0

In [ ]:
for col in text_columns:
  print(col,df[col].nunique())
  print("-"*30)

OrderID 100000
------------------------------
CustomerID 43233
------------------------------
CustomerName 200
------------------------------
ProductID 50
------------------------------
ProductName 50
------------------------------
Category 6
------------------------------
Brand 10
------------------------------
PaymentMethod 6
------------------------------
OrderStatus 5
------------------------------
City 20
------------------------------
State 13
------------------------------
Country 5
------------------------------
SellerID 1999
------------------------------
Month 12
------------------------------
WeekDay 7
------------------------------
Weekend 1
------------------------------

# FEATURE ENGINEERING

In [ ]:
df['OrderDate']=pd.to_datetime(df['OrderDate'])
df['Year']=df['OrderDate'].dt.year

df['MonthNo']=df['OrderDate'].dt.month

df['Month'] = df['OrderDate'].dt.month_name()

df['Quarter']=df['OrderDate'].dt.quarter

df['WeekDay']=df['OrderDate'].dt.day_name()

In [ ]:
df['SalesBeforeDiscount']=df['Quantity'] * df['UnitPrice']

df['DiscountAmount']=df['SalesBeforeDiscount'] * (df['Discount']/100)

df['NetSales']=df['SalesBeforeDiscount'] - df['DiscountAmount']

df['ApproxProfit']=df['NetSales']-df['ShippingCost']-df['Tax']

In [ ]:
df.head()

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID,Year,MonthNo,Month,Quarter,WeekDay,Weekend,SalesBeforeDiscount,DiscountAmount,NetSales,ApproxProfit
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967,2023,1,January,1,Tuesday,No,319.77,0.000000,319.770000,319.680000
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298,2023,12,December,4,Saturday,No,251.37,0.125685,251.244315,230.404315
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,0.10,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908,2022,5,May,2,Tuesday,No,105.09,0.105090,104.984910,91.504910
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,0.15,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164,2023,7,July,3,Tuesday,No,167.90,0.251850,167.648150,150.698150
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,0.25,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411,2023,2,February,1,Saturday,No,1031.28,2.578200,1028.701800,980.801800

In [ ]:
print("Total Revenue : $",round(df["TotalAmount"].sum(),2))

print("Total Orders :",df["OrderID"].nunique())

print("Total Customers :",df["CustomerID"].nunique())

print("Total Products :",df["ProductID"].nunique())

print("Total Sellers :",df["SellerID"].nunique())

print("Average Order Value : $",round(df["TotalAmount"].mean(),2))

print("Average Quantity :",round(df["Quantity"].mean(),2))

print("Average Shipping : $",round(df["ShippingCost"].mean(),2))

print("Average Discount :",round(df["Discount"].mean(),2))

Total Revenue : $ 91825647.92
Total Orders : 100000
Total Customers : 43233
Total Products : 50
Total Sellers : 1999
Average Order Value : $ 918.26
Average Quantity : 3.0
Average Shipping : $ 7.41
Average Discount : 0.07

In [ ]:
df.to_csv("cleaned_amazon_orders.csv", index=False)